### ISSUE TITLE
Recommended settings for JLCPCB

### ISSUE THREAD

**Issue by idank** [0xCB-dev/0xCB-Helios#1]
I was able to get a gerber/bom/cpl loaded properly on jlc but the costs are extremely high. Do you have any suggestions on how to bring those down a bit? Or is this not economically viable to order in small quantities? (a few dozen)

FYI main reason I look into it is because keeb.supply doesn't ship outside the EU.

**Comment by Jakob170201** [comment]
Hey! Thank you for your interest! We can get such low prices, because we order in large quantities. I'm talking over 150 controllers at a time. With jlc you have a lot of fixed fees. When you order more the fees don't get more expensive resulting In cheaper costs overall. Things like Enig finish also cost extra.

We currently have a shipment of Helios controllers on the way to Ringerkeys in the US. Those will go InStock soon, so if you will be able to get them worldwide shortly.

**Comment by idank** [comment]
Yeah that makes sense. I'm still curious how cheap one can get with optimal settings, for example I noticed this increased costs a bit when adding assembly:

> Your PCB size is 33.02mm*17.78mm, JLCPCB will help you add edge rails and enlarge
> 
> the size to 71.02mm*71.78mm.

I guess a complete panel will be more cost effective?

**Comment by Jakob170201** [comment]
Yes we order them in panels of 10 controllers. The files are also here in the GitHub.

**Comment by idank** [comment]
Oh it's under rev1.0/kikit, nice! Are there any considerations / settings that need to be picked to get one made from JLCPCB?

**Comment by opaldes** [comment]
Dont forget that each pcb holds 10 Helios Controller and you order 5pcbs here so 50 Helios. Standard costs me around 6 euro each without shipping question is do you need 50 Helios.

**Comment by Ardakilic** [comment]
Hello, can you confirm the board is indeed 4 layers? Thanks!

**Comment by Jakob170201** [comment]
Yes. Helios is a 4 layer board.
