### ISSUE TITLE
Flashing does not work

### ISSUE THREAD

**Issue by bfloch** [0xCB-dev/0xCB-Helios#2]
Got the device via Keebd.
The instructions in the repo do not work. Instead I went with the .hex file from the Keebd website (cobra_default.hex). It copies the .uf2 to the drive but then nothing.
Pressing the reset button or not does not make a difference - it always goes back into bootloader mode.

Can you help guide me through the process - or point to clearer instructions? Thanks.

**Comment by medoix** [comment]
Helios firmware files end in .uf2 not .hex (due to running the RP2040 chip) so it sounds like you downloaded the wrong file.

[QMK has converters](https://docs.qmk.fm/#/feature_converters?id=converters) that will build the right firmware file.

Also when the Helios enters bootloader mode a volume will be mounted and you simply need to drag/drop the .uf2 file onto it to program the controller.

**Comment by bfloch** [comment]
Ok got it working.
```
qmk config user.keymap=stateoff  # Can be anything / username
qmk config user.keyboard=contra
# Generate json and download at https://config.qmk.fm/#/contra/LAYOUT_planck_mit
# Plug in Helios (use button if not in bootloader mode)
qmk flash -c generated.json  -e CONVERT_TO=helios
```
This made it for me. Thanks for the hints.
